# Generated by Django 2.2.5 on 2019-09-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas_dua', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='sherk.jpg', upload_to='img/'),
            preserve_default=False,
        ),
    ]
